sudo: required
language: node_js
node_js:
#- "node"
  - "12"
services:
  - xvfb
env:
global:
    - BACKEND_CPU=true EXCLUDE_UNCOMPRESSED=true
matrix:
    - ENV=browser
    - ENV=node
addons:
chrome: stable
install: npm install
script:
  - npm start
